<?php

namespace BookRater\RaterBundle\Repository;

use Doctrine\ORM\EntityManagerInterface;
use \Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends EntityRepository
{

    /**
     * @var QueryBuilder
     */
    private $queryBuilder;

    public function __construct($em, Mapping\ClassMetadata $class)
    {
        parent::__construct($em, $class);
        $this->queryBuilder = $this->createQueryBuilder('book');
    }

    public function findAllOrderedByNameQB()
    {
        return $this->queryBuilder
            ->orderBy('book.title');
    }

    public function findAllWhereTitleLike(string $titleFragment)
    {
        return $this->queryBuilder
            ->select('book')
            ->where($this->queryBuilder->expr()->like('book.title', ":titleFragment"))
            ->orderBy('book.title')
            ->setParameter('titleFragment', '%'.$titleFragment.'%')
            ->getQuery()
            ->getResult();
    }
}
