<?php

namespace BookRater\RaterBundle\Repository;

use \Doctrine\ORM\EntityRepository;

/**
 * ReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewRepository extends EntityRepository
{

    public function getLatestQuery()
    {
        $qb = $this->createQueryBuilder('review');
        return $qb
            ->addOrderBy('review.created')
            ->getQuery();
    }

    public function getLatestByBookTitleLike($titleLike)
    {
        $qb = $this->createQueryBuilder('review');
        return $qb
            ->leftJoin('review.bookReviewed', 'book_reviewed')
            ->andWhere($qb->expr()->like('book_reviewed.title', ':titleLike'))
            ->setParameter('titleLike', '%'.$titleLike.'%')
            ->addOrderBy('review.created', 'DESC')
            ->getQuery();
    }

}
