<?php

namespace BookRater\RaterBundle\Repository;

use \Doctrine\ORM\EntityRepository;

/**
 * ReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewRepository extends EntityRepository
{

    public function getLatestQuery()
    {
        return $this->createQueryBuilder('review')
            ->addOrderBy('review.created')
            ->getQuery();
    }
}
