<?php

namespace BookRater\RaterBundle\Repository;

use \Doctrine\ORM\EntityRepository;

/**
 * ReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewRepository extends EntityRepository
{

    public function getLatest(int $limit = 10, int $offset = 0)
    {
        return $this->createQueryBuilder('review')
            ->addOrderBy('review.created')
            ->setFirstResult($offset)
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult();
    }
}
