bookrater_home:
    path:     /
    defaults: { _controller: BookRaterRaterBundle:Page:index }

bookrater_about:
    path: /about
    defaults: { _controller: BookRaterRaterBundle:Page:about }

bookrater_contact:
    path: /contact
    defaults: { _controller: BookRaterRaterBundle:Page:contact }

bookrater_author_view:
    path:     /view/author/{id}
    defaults: { _controller: BookRaterRaterBundle:Author:view }
    methods: [GET]
    requirements:
        id: \d+

bookrater_author_create:
    path:     /create/author
    defaults: { _controller: BookRaterRaterBundle:Author:create }
    methods: [GET, POST]

bookrater_author_edit:
    path:     /edit/author/{id}
    defaults: { _controller: BookRaterRaterBundle:Author:edit }
    methods: [GET, POST]
    requirements:
        id: \d+

bookrater_book_view:
    path:     /view/book/{id}
    defaults: { _controller: BookRaterRaterBundle:Book:view }
    methods: [GET]
    requirements:
        id: \d+

bookrater_book_create:
    path:     /create/book
    defaults: { _controller: BookRaterRaterBundle:Book:create }
    methods: [GET, POST]

bookrater_book_edit:
    path:     /edit/book/{id}
    defaults: { _controller: BookRaterRaterBundle:Book:edit }
    methods: [GET, POST]
    requirements:
        id: \d+

#bookrater_author_delete:
#    path:     /author/delete/{id}
#    defaults: { _controller: BookRaterRaterBundle:Author::delete }
#    methods: [GET, DELETE]
#    requirements:
#        id: \d+