bookrater_home:
    path:     /
    defaults: { _controller: BookRaterRaterBundle:Home:index }

bookrater_about:
    path: /about
    defaults: { _controller: BookRaterRaterBundle:Home:about }

bookrater_contact:
    path: /contact
    defaults: { _controller: BookRaterRaterBundle:Home:contact }

bookrater_author_view:
    path:     /view/author/{id}
    defaults: { _controller: BookRaterRaterBundle:Author:view }
    requirements:
        id: \d+

bookrater_author_create:
    path:     /create/author
    defaults: { _controller: BookRaterRaterBundle:Author:create }

bookrater_author_edit:
    path:     /edit/author/{id}
    defaults: { _controller: BookRaterRaterBundle:Author:edit }
    requirements:
        id: \d+

bookrater_book_view:
    path:     /view/book/{id}
    defaults: { _controller: BookRaterRaterBundle:Book:view }
    requirements:
        id: \d+

bookrater_book_create:
    path:     /create/book
    defaults: { _controller: BookRaterRaterBundle:Book:create }

bookrater_book_edit:
    path:     /edit/book/{id}
    defaults: { _controller: BookRaterRaterBundle:Book:edit }
    requirements:
        id: \d+

bookrater_book_search:
    path:     /
    defaults: { _controller: BookRaterRaterBundle:Book:searchBook }
#    requirements:
#        id: \d+

#bookrater_author_delete:
#    path:     /author/delete/{id}
#    defaults: { _controller: BookRaterRaterBundle:Author::delete }
#    methods: [GET, DELETE]
#    requirements:
#        id: \d+
#bookrater_review_index:
#    path:     /index/review
#    defaults: { _controller: BookRaterRaterBundle:Review:index }

bookrater_review_list:
    path:     /reviews
    defaults: { _controller: BookRaterRaterBundle:Review:list }

bookrater_review_view:
    path:     /view/review/{id}
    defaults: { _controller: BookRaterRaterBundle:Review:view }
    requirements:
        id: \d+

bookrater_review_edit:
    path:     /edit/review/{id}
    defaults: { _controller: BookRaterRaterBundle:Review:edit }
    requirements:
        id: \d+

bookrater_review_create:
    path:     /create/review
    defaults: { _controller: BookRaterRaterBundle:Review:create }

bookrater_review_delete:
    path:     /delete/review/{id}
    defaults: { _controller: BookRaterRaterBundle:Review:delete }
    requirements:
        id: \d+
