bookrater_home:
    path:     /
    defaults: { _controller: BookRaterRaterBundle:Page:index }

bookrater_about:
    path: /about
    defaults: { _controller: BookRaterRaterBundle:Page:about }

bookrater_contact:
    path: /contact
    defaults: { _controller: BookRaterRaterBundle:Page:contact }