services:
    BookRater\RaterBundle\:
        resource: '../../*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../{Entity,Api/ApiProblem*,Pagination/PaginatedCollection}'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    BookRater\RaterBundle\Controller\:
        resource: '../../Controller/*'
        public: true
        autowire: true
        autoconfigure: true
        tags: ['controller.service_arguments']
#
    BookRater\RaterBundle\EventListener\ApiExceptionSubscriber:
        arguments: ['%kernel.debug%', '@BookRater\RaterBundle\Api\ResponseFactory', '@logger']
        tags:
            - { name: kernel.event_subscriber }

    jwt_token_authenticator: '@BookRater\RaterBundle\Security\JwtTokenAuthenticator'
    custom_hateoas_json_serializer: '@BookRater\RaterBundle\Serializer\CustomHATEOASJsonSerializer'
