imports:
    - { resource: '@BookRaterFixturesBundle/Resources/config/services.yml' }
    - { resource: '@BookRaterRedirectBundle/Resources/config/services.yml' }

parameters:
    #parameter_name: value

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
