imports:
    - { resource: '@BookRaterFixturesBundle/Resources/config/services.yml' }
    - { resource: '@BookRaterRedirectBundle/Resources/config/services.yml' }

parameters:
    #parameter_name: value

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    app.form.registration:
        class: BookRater\RaterBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }