imports:
    - { resource: '../../src/BookRater/FixturesBundle/Resources/config/services.yml' }

parameters:
    #parameter_name: value

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    app.form.registration:
        class: BookRater\RaterBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }

    app.redirect_after_registration_subscriber:
        class: BookRater\RedirectBundle\EventListener\RedirectAfterRegistrationSubscriber
        autowire: true
        tags:
            - { name: kernel.event_subscriber }
