services:
    app.redirect_after_registration_subscriber:
        class: BookRater\RedirectBundle\EventListener\RedirectFOSUserSubscriber
        arguments: ['@router']
        tags:
            - { name: kernel.event_subscriber }
