services:
    app.redirect_after_registration_subscriber:
        class: BookRater\RedirectBundle\EventListener\RedirectFOSUserSubscriber
        autowire: true
        tags:
            - { name: kernel.event_subscriber }