api_token:
    resource: '@BookRaterRaterBundle/Controller/Api/TokenController.php'
    type:     annotation

api_author:
    resource: '@BookRaterRaterBundle/Controller/Api/AuthorController.php'
    type:     annotation

api_book:
    resource: '@BookRaterRaterBundle/Controller/Api/BookController.php'
    type:     annotation
