bookrater_home:
    path:     /
    defaults: { _controller: BookRaterRaterBundle:Home:index }

bookrater_about:
    path: /about
    defaults: { _controller: BookRaterRaterBundle:Home:about }

bookrater_contact:
    path: /contact
    defaults: { _controller: BookRaterRaterBundle:Contact:create }

bookrater_messages:
    path: /admin/messages
    defaults: { _controller: BookRaterRaterBundle:Contact:list }