bookrater_book_list:
    path:     /list
    defaults: { _controller: BookRaterRaterBundle:Web\Book:list }
    options:
        expose: true

bookrater_book_create:
    path:     /create
    defaults: { _controller: BookRaterRaterBundle:Web\Book:create }

bookrater_book_view:
    path:     /{title}
    defaults: { _controller: BookRaterRaterBundle:Web\Book:view }

bookrater_book_edit:
    path:     /edit/{id}
    defaults: { _controller: BookRaterRaterBundle:Web\Book:edit }
    requirements:
        id: \d+

bookrater_book_create_review:
    path:     /edit/{id}/review
    defaults: { _controller: BookRaterRaterBundle:Web\Book:addReview }
    requirements:
        id: \d+
