bookrater_home:
    path:     /
    defaults: { _controller: BookRaterRaterBundle:Web\Home:index }

bookrater_about:
    path: /about
    defaults: { _controller: BookRaterRaterBundle:Web\Home:about }

bookrater_contact:
    path: /contact
    defaults: { _controller: BookRaterRaterBundle:Web\Message:create }

bookrater_messages:
    path: /admin/messages
    defaults: { _controller: BookRaterRaterBundle:Web\Message:list }