bookrater_review_list:
    path:     /
    defaults: { _controller: BookRaterRaterBundle:Review:list }

bookrater_review_view:
    path:     /view/{id}
    defaults: { _controller: BookRaterRaterBundle:Review:view }
    requirements:
        id: \d+

bookrater_review_edit:
    path:     /edit/{id}
    defaults: { _controller: BookRaterRaterBundle:Review:edit }
    requirements:
        id: \d+

bookrater_review_create:
    path:     /create
    defaults: { _controller: BookRaterRaterBundle:Review:create }

bookrater_review_delete:
    path:     /delete/{id}
    defaults: { _controller: BookRaterRaterBundle:Review:delete }
    requirements:
        id: \d+
