bookrater_author_list:
    path:     /
    defaults: { _controller: BookRaterRaterBundle:Author:list }

bookrater_author_create:
    path:     /create
    defaults: { _controller: BookRaterRaterBundle:Author:create }

bookrater_author_view:
    path:     /{lastName}/{firstName}
    defaults: { _controller: BookRaterRaterBundle:Author:view }
    requirements:
        lastName: "[A-Za-z']+"
        firstName: \w+

bookrater_author_edit:
    path:     /edit/{lastName}/{firstName}
    defaults: { _controller: BookRaterRaterBundle:Author:edit }
    requirements:
        lastName: "[A-Za-z']+"
        firstName: \w+